# Generated by Django 6.0.2 on 2026-04-06 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Port Scan', 'Port Scan'), ('Traffic Spike', 'Traffic Spike'), ('Brute Force', 'Brute Force'), ('Unknown Anomaly', 'Unknown Anomaly')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(default='Medium', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('packet_size', models.IntegerField()),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP')], max_length=10)),
                ('duration', models.FloatField(default=0.0)),
                ('prediction', models.IntegerField()),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Safe', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
